### ISSUE TITLE
上海徐汇区us embassy只有两个污染物报错

### ISSUE THREAD

**Issue by Victor2Code** [Victor2Code/air-quality#1]
Traceback (most recent call last):
  File "history_data.py", line 88, in single_page_history
    driver.find_element_by_xpath('//*[@id="history-kind-dropdown"]/ul/li[{}]'.format(i)).click()
  File "/home/fuhx/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/fuhx/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/fuhx/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/fuhx/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="history-kind-dropdown"]/ul/li[3]"}
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 3.10.0-862.14.4.el7.x86_64 x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "history_data.py", line 160, in <module>
    main(driver,link,'utf-8')
  File "history_data.py", line 156, in main
    recursion_body(driver,province[0],province[1],province[2],f)
  File "history_data.py", line 147, in recursion_body
    recursion_body(driver,location[0],location[1],location[2],file_indicator)
  File "history_data.py", line 147, in recursion_body
    recursion_body(driver,location[0],location[1],location[2],file_indicator)
  File "history_data.py", line 147, in recursion_body
    recursion_body(driver,location[0],location[1],location[2],file_indicator)
  File "history_data.py", line 138, in recursion_body
    history_data=single_page_history(driver,url,name,AQI,file_indicator)
  File "history_data.py", line 90, in single_page_history
    return result 
NameError: name 'result' is not defined

**Comment by Victor2Code** [comment]
已解决，在single_page_history函数中的
```python
except Exception as e:
return result
```
改为
```python
except Exception as e:
return 'Success'
```
